import "Another.Component.idl";

namespace CppWinRTComponent
{
    [default_interface]
    runtimeclass Component
    {
		Component();
        String Echo(String input);

		CppWinRTComponent.Another.Component Another{ get; set; };
    }
}
